version: '2'

services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    image: christosp/test_exim
    ports:
      - '80:80'
      - "443:443"
    container_name: test_exim
    volumes:
      - ./src/:/var/www/html/


